<?php
require('config/connexion.php');
$query = $db->prepare('SELECT * FROM annonces');
$query->execute();
$annonces = $query->fetchAll(PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Connexion / Inscription</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    
  </header>

  <section>
    <h1>Connectez-vous</h1>
    <form action="logic/connexion.php" method="post" >
      <label for="email">Adresse e-mail:</label>
      <input type="email" id="email" name="email" required>

      <label for="password">Mot de passe:</label>
      <input type="password" id="password" name="password" required>

      <button type="submit" name = "valider">Se Connecter</button>
    </form>

    <p>ou</p>

    <h1>Inscrivez-vous</h1>
    <form action="/register" method="post">
      <label for="name">Nom:</label>
      <input type="text" id="name" name="name" required>
      
      <label for="name">prénom:</label>
      <input type="text" id="name" name="name" required>

      <label for="email">Adresse e-mail:</label>
      <input type="email" id="email" name="email" required>

      <label for="password">Mot de passe:</label>
      <input type="password" id="password" name="password" required>

      <button type="submit">S'inscrire</button>
    </form>

  </section>

  <footer>
    
  </footer>
</body>
</html>