<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Catalogue des Annonces</title>
   <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
      <nav>
        <ul>
          <li><a href="#">Accueil</a></li>
          <li><a href="#">Profil</a></li>
          <li><a href="#">Déconnexion</a></li>
        </ul>
      </nav>
  </header>
  <section>
      <h2>Catalogue des Annonces</h2>
            <div class="annonce">
              <img src="https://picsum.photos/200/300" alt="Image de l'annonce 1">
              <h3>Titre de l'annonce 1</h3>
              <p>extrait:</p>
              <p>Description de l'annonce 1</p>
              <button>Voir Détails</button>
            </div>

            <div class="annonce">
              <img src="https://picsum.photos/200/300" alt="Image de l'annonce 2">
              <h3>Titre de l'annonce 2</h3>
              <p>extrait:</p>
              <p>Description de l'annonce 2.</p>
              <button>Voir Détails</button>
            </div>
            
            <div class="annonce">
              <img src="https://picsum.photos/200/300" alt="Image de l'annonce 3">
              <h3>Titre de l'annonce 3</h3>
              <p>extrait:</p>
              <p>Description de l'annonce 3.</p>
              <button>Voir Détails</button>
            </div>

  </section>

  <footer>
        <a href="#">Contact</a>
  </footer>
</body>
</html>
  
   
