<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Détails de l'Annonce</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <main class="container">
    <header>
      <h1>Plateforme Annonces</h1>
      <nav>
        <ul>
          <li><a href="#">Accueil</a></li>
          <li><a href="#">Profil</a></li>
          <li><a href="#">Déconnexion</a></li>
        </ul>
      </nav>
    </header>

    <section id="annonce-1">
      
      <div id="details-1">
        <h2>Titre de l'annonce</h2>
        <p>Description détaillée de l'annonce.</p>
        <p>Prix: </p>
        <p>Localisation: Ville, Pays</p>
        <button class="favorite">Ajouter aux Favoris</button>
        <button class="remove-favorite">Retirer des Favoris</button>
      </div>
    </section>
    
    <section id="annonce-2">
      
      <div id="details-2">
        <h2>Titre de l'annonce</h2>
        <p>Description détaillée de l'annonce.</p>
        <p>Prix: </p>
        <p>Localisation: Ville, Pays</p>
        <button class="favorite">Ajouter aux Favoris</button>
        <button class="remove-favorite">Retirer des Favoris</button>
      </div>
    </section>
    
    <section id="annonce-3">
      
      <div id="details-3">
        <h2>Titre de l'annonce</h2>
        <p>Description détaillée de l'annonce.</p>
        <p>Prix: </p>
        <p>Localisation: Ville, Pays</p>
        <button class="favorite">Ajouter aux Favoris</button>
        <button class="remove-favorite">Retirer des Favoris</button>
      </div>
    </section>
  </main>
</body>
</html>